version: "3"

networks:
  web:
    external: true

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    labels:
      - traefik.enable=false
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 9000:9000
    restart: unless-stopped

  traefik:
    image: traefik
    container_name: traefik
    volumes:
      - /mnt/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /mnt/traefik/traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml
      - /mnt/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    ports:
      - 80:80
      - 443:443
      - 2022:2022
    restart: unless-stopped

volumes:
  portainer_data:
